### ISSUE TITLE
#1 Add navigation

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#1]
# Value Proposition

**As a** user
**I want to** I want to see a navbar
**So that** I can switch between the create page and the home page

# Description

![Image](https://user-images.githubusercontent.com/101993818/184602172-fa016151-0be7-47df-88e1-7b7a4e692571.png)

# Acceptance Criteria

- [ ] An icon and title("Home") for the home page
- [ ] An icon and title("Create") for the create page
- [ ] When clicking on a nav button, change the page belonging to the button
- [ ] When clicking on a nav button, the icon is filled and the other is unfilled
- [ ] The navbar should stick on the bottom of the viewport
- [ ] The titles of the respective pages are at the top

# Tasks

- [ ] Create a ```Navbar``` component
- [ ] Add icons and titles to ```Navbar```
- [ ] Fix the ```Navbar``` at the bottom of the viewport
- [ ] Add onClick function to toggle between filled and unfilled
- [ ] Add function to switch between pages
- [ ] Add page titles
- [ ] Write test to check if onClick the respective page is shown
- [ ] Write test to check if onClick the icon is filled and other unfilled

# Complexity

L

**Comment by aclaes** [comment]
Hi Vlady,

this should not be this first user story. 

It doesn't provide a value to the user.

Please remember no empty pages, no placeholders for further implementation, no buttons without functions.

Your first user story should be concerned about a form or rendering static content.

Switching between two pages without content has no use. This could be a valid user story later on, if there is content that can be shown on thos pages
