### ISSUE TITLE
#7 Bookmark videos

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#12]
# Value Proposition

**As a** user
**I want to** bookmark videos
**So that** I can rewatch them later

# Description

![Image](https://user-images.githubusercontent.com/101993818/185762445-8a9af999-1c26-468a-b354-2ad42e451a89.png)

# Acceptance Criteria

- [x] Bookmark icon is on each video
- [x] Clicking on bookmark button shows filled bookmark icon
- [x] Bookmarks page with all bookmarked videos
- [x] Clicking on bookmark button shows the video on the bookmarks page
- [x] Clicking on bookmarked a video the video is no longer bookmarked and is removed from bookmarks page

# Tasks

- [x] Add bookmark icon to each video
- [x] Reposition the delete, edit and bookmark icons
- [x] Add bookmark page
- [x] Add bookmark icon to navbar and link to bookmarks page
- [x] Create function to show bookmarked videos on bookmarks page
- [x] Add more dummy data to Store to display more videos for more variety

# Complexity

L
