### ISSUE TITLE
#6 Add confirmation text after submit

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#13]
# Value Proposition

**As a** user
**I want to** have a visual feedback after submitting my form
**So that** I can be sure, the video was added

# Description

![Image](https://user-images.githubusercontent.com/101993818/185764047-483b0827-6f58-45cd-844d-c1579d2384b4.png)

# Acceptance Criteria

- [x] Confirmation text is shown after submitting the form
- [x] After a few seconds, the text box disappears

# Tasks

- [x] Add text box with confirmation text
- [x] Write function that the text box disappears after a few seconds
- [x] Delete list showing title and url

# Complexity

S
