### ISSUE TITLE
#9 Add categories

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#14]
# Value Proposition

**As a** user
**I want to** have videos categories
**So that** I can differentiate them by category

# Description

![Image](https://user-images.githubusercontent.com/101993818/185766770-b0868043-b776-4fdd-8b21-53fb5e2e1bad.png)

![Image](https://user-images.githubusercontent.com/101993818/185764761-c686fb5d-a2c4-4895-b7e8-4c044001688f.png)

# Acceptance Criteria

- [x] The form has a dropdown to choose the category
- [x] The category is displayed on each video

# Tasks

- [x] Add dropdown to form
- [x] Add category to each VideoCard

# Complexity
S
