### ISSUE TITLE
#11 Explore categories

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#15]
# Value Proposition

**As a** user
**I want to** browse through categories
**So that** I can see all videos related to a category

# Description

![Image](https://user-images.githubusercontent.com/101993818/185767776-24b2bcb2-9173-43f3-abe7-2f5f8007f04c.png)

![Image](https://user-images.githubusercontent.com/101993818/185768392-6c19d4f0-8606-4a06-aa0d-7bbe63a9acd5.png)

# Acceptance Criteria

- [x] Explore page shows all categories
- [x] The navbar has an explore icon linked to the explore page
- [x] Videos belonging to each related category are shown on the explore page
- [x] The videos are a smaller version showing just the title 
- [x] For each category, the videos can be scrolled horizontally
- [x] Clicking on a video, the user will be redirected to a feed with all videos related to the category and showing the clicked video at the top

# Tasks

- [x] Create an explore page
- [x] Add explore icon to the navbar and link to the explore page
- [x] Show all categories on the explore page
- [x] Create a ```Categories``` component
- [x] Filter videos to show in the related category on explore page
- [x] Create horizontal scroll for categorized videos
- [x] Create a category feed page ([id].js) to show all videos related to the category like in the home feed 

# Complexity

XXL
