### ISSUE TITLE
#10 Add categories to edit form

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#17]
# Value Proposition

**As a** user
**I want to** edit the category of the video
**So that** I can change the category, if it was chosen falsely

# Description

![Image](https://user-images.githubusercontent.com/101993818/185811004-c93d1a23-1d7d-489e-b00f-327af4158a7a.png)

# Acceptance Criteria

- [x] A dropdown is showing all categories
- [x] The edit form has a dropdown to choose the category
- [x] The changed category is displayed on the edited video

# Tasks

- [x] Add dropdown to the edit form
- [x] Add the changed category to the edited video

# Complexity
S
