### ISSUE TITLE
#8 Add cancel button to edit form

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#19]
# Value Proposition

**As a** user
**I want to** cancel the edit form
**So that** I can go back to the home page if I changed my mind about editing

# Description

![Image](https://user-images.githubusercontent.com/101993818/185915327-25f4e4fc-98ff-415d-baf3-f8c9063bf7e7.png)

# Acceptance Criteria

- [x] Cancel button on edit form
- [x] On click redirects back to home page

# Tasks

- [x] Add cancel button to edit form
- [x] Add function to redirect back to home page
- [x] Position cancel and delete buttons

# Complexity

S
