### ISSUE TITLE
#1 Create a new Video Card

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#2]
# Value Proposition

**As a** user
**I want to** add a new video card to the feed
**So that** I can increase the variety of videos for my kid

# Description

![Form](https://user-images.githubusercontent.com/101993818/184644301-bab28c55-01bf-42fa-9ae0-2dbd1a934e26.png)

# Acceptance Criteria

- [x] An input field for the YouTube video link is displayed (label: "YouTube link")
- [x] An input field for the video title is displayed (label: "Video title")
- [x] A submit button is displayed
- [x] All form fields are required
- [x] After submitting the form, the title and link are displayed at the end list of all entries

# Tasks

- [x] Create a ```Form``` component with two input fields
- [x] Add a submit button to the form
- [x] Create a ```StyledForm``` component
- [x] Create a ```StyledInput``` component
- [x] Create a ```StyledButton``` component
- [x] Add state handling (with zustand.js)
- [x] Add submitted input to stored data variable in zustand
- [x] Add ```event.preventDefault()``` to the form submit
- [x] Create form validation
- [x] Write tests to check the form validation
- [x] Write tests to check if the video was added to the list

# Complexity

XL

**Comment by alexclaes** [comment]
Hi Vlady,

good user story!

As of this point there are no different pages and no navigation. Therefore the AC "After submitting the form the user is redirected to the home page" can never be accomplished.

You should rewrite this AC; something like this: "After submitting the form, the title and link are displayed at the end list of all entries"

You should remove the navigation bar from the scribble, because this feature will not yet be available.

**Comment by ahohnsen** [comment]
Hey Vlady,

Nice job. Just one minor suggestion:

>  After submitting the form, the title and link are displayed at the end list of all entries

It would be really nice to also see the list in your scribble 🙂

**Comment by RobertBReich** [comment]
Hey Vlady,

looks good. 👍
