### ISSUE TITLE
#12 Add confirmation text after submit of edit form

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#22]
# Value Proposition

**As a** user
**I want to** have a visual feedback after submitting my edit form
**So that** I can be sure, the video was edited

# Description

![Image](https://user-images.githubusercontent.com/101993818/186698273-8bda60bb-5e66-4654-80b0-67626b8ae9d1.png)

# Acceptance Criteria

- [x] Confirmation text is shown after submitting the edit form
- [x] After a few seconds, the text box disappears

# Tasks

- [x] Add text box with confirmation text
- [x] Add function that the text box disappears after a few seconds

# Complexity

XS
