### ISSUE TITLE
#13 Search for YouTube playlist

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#26]
# Value Proposition

**As a** user
**I want to** search for a YouTube channel to get its playlists
**So that** I can see each playlist and the titles and URLs of the videos in a playlist 

# Description

![Image](https://user-images.githubusercontent.com/101993818/186877187-d5c67faf-edab-4dea-9a90-d9dc7c66fb84.png)

# Acceptance Criteria

- [x] Input field with search bar
- [x] Clicking on the Search button, all playlists of a specific channel are shown
- [x] The URLs and titles of the videos in the playlist are shown as a list

# Tasks

- [x] Create a new form with input field and search button
- [x] Fetch YouTube Data API v3
- [x] onSubmit search for channel and retrieve channel ID
- [x] Fetch with the channel ID for playlists
- [x] Fetch with the playlist ID for all playlist videos
- [x] Get all video IDs
- [x] Interpolate video IDs into YouTube embed link
- [x] Create YouTubePlaylists component
- [x] Display interpolated links and video titles in YouTubePlaylists
- [x] Show YouTubePlaylists on the create page after submitting on the Search button

# Complexity

XXL

**Comment by RobertBReich** [comment]
Hi Vlady,
fetchy fetchy, hm? 😁

looks good to me. 👍

cheers
R.
