### ISSUE TITLE
#14 Redesign Playlist component

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#27]
# Value Proposition

**As a** user
**I want to** see a playlist displaying all related videos with thumbnails, titles and URLs
**So that** I can see the difference between the videos

# Description

![Image](https://user-images.githubusercontent.com/101993818/186893842-61c241ce-60b1-4226-8c4b-c8b3d36b2bd8.png)

# Acceptance Criteria

- [ ] The playlist displays all videos of the selected playlist
- [ ] The video details are shown at each video

# Tasks

- [ ] Create `PlaylistVideoCard` component
- [ ] Display `PlaylistVideoCard` for each video in the playlist
- [ ] Display details of the videos in `PlaylistVideoCard`

# Complexity

M

**Comment by RobertBReich** [comment]
Hi Vlady,
i think the Acceptance Criteria should be more user or behaviour focused. So it's more like:
- The playlist should display all videos of the selected playlist
- The user can see / access the details about that video

Other than that, it looks cool.

cheers
R.
