### ISSUE TITLE
#14 Add playlist video to feed

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#28]
# Value Proposition

**As a** user
**I want to** to add a video from the playlist to the feed
**So that** watch them in the feed

# Description

![Image](https://user-images.githubusercontent.com/101993818/186926494-dc9abf5e-5e44-44e5-bf8d-79aa887a3dc3.png)

![Image](https://user-images.githubusercontent.com/101993818/186926510-ff775c46-0495-4ef9-8abc-11dbac3c7c13.png)

# Acceptance Criteria

- [x] Each video in the playlist has a category dropdown and an Add button
- [x] The category is required
- [x] On Add button click the video is displayed in the feed

# Tasks

- [x] Add category dropdown to each `PlaylistVideoCard`
- [x] Add Add button  to each `PlaylistVideoCard`
- [x] Validate the form
- [x] Add onSubmit function to submit data to Store and display in feed

# Complexity

M

**Comment by ckskr** [comment]
Hi Vlady, 
I don't fully understand what ur goal is here. 
You have a playlist but still you want to add a video from that playlist to the feed (which is basically just another playlist)?
Why cant the user watch it in the playlist it already is in?

**Comment by Gw3i** [comment]
@ckskr Good point, I've not mentioned that it belongs to the search function. I'll change it

**Comment by ckskr** [comment]
Ok, now with the updated picture I can understand better. However I guess it would also be good to explain it in the text. For next time ;)
