### ISSUE TITLE
#15 Add confirmation message after added video

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#29]
# Value Proposition

**As a** user
**I want to** have a visual feedback after clicking on the Add button
**So that** I can be sure, the video was added

# Description

![Image](https://user-images.githubusercontent.com/101993818/186935746-6337ba96-0223-410d-abfd-f027bd60ec3f.png)

# Acceptance Criteria

- [ ] Confirmation text is shown after clicking on the Add button
- [ ] After clicking on the Add button, the button for that videos is disabled
- [ ] After a few seconds, the text box disappears

# Tasks

- [ ] Add text box with confirmation text
- [ ] Add function that the text box disappears after a few seconds
- [ ] Add function to disable the button

# Complexity

XS

**Comment by j-eick** [comment]
Your scribble says "edited" instead of "added". 

**Suggestion/idea**
Would be nice, if the "add" button disappears for the respective video after the user clicked the add-button. That would help the user knowing which videos he/she already added.

**Comment by Gw3i** [comment]
@j-eick That is a great idea! I will implement it
