### ISSUE TITLE
#2 Display video cards

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#3]
# Value Proposition

**As a** user
**I want to** see all my submitted videos in my feed
**So that** I can watch a variety of videos in one place 

# Description

![Image](https://user-images.githubusercontent.com/101993818/184819674-7f1b2755-e866-4fc9-afb1-5bade8d5436d.png)

![Link on create page](https://user-images.githubusercontent.com/101993818/184706326-993ad9ec-f35b-4214-9d46-de52df827342.png)

# Acceptance Criteria

- [x] The video card is displayed
- [x] The video starts playing when the play button is clicked
- [x] The video stops playing when clicking on the video or using the video player controls
- [x] The video's  title is displayed
- [x] A link on the home page is displayed redirecting to the create page
- [x] A link on the create page is displayed redirecting to the home page

# Tasks

- [x] Create ```VideoCard``` component
- [x] Render the ```VideoCard``` component on the index page
- [x] Take the submitted data from form and render it in the card component
- [x] Render YouTube link to show in the card 
- [x] Render the title to show in the bottom left of the card
- [x] Add links to pages 
- [ ] Write tests to check if the video is rendered on the index page
- [ ] Write tests to check if the video is playing
- [x] Write tests to check if the video's title is showing

# Complexity

L

**Comment by RobertBReich** [comment]
Task 6: "rendere", 
Sonst sieht gut aus.

**Comment by ahohnsen** [comment]
Hey Vlady,

Great! 💪🏼 I have a few suggestions:

Scribble:
- It should be as realistic as possible, so it is easy to understand (e.g. filled with real content). In your scribble I see an empty box on the bottom left of the screen. What is this box supposed to be? If it is a label/button etc. there should be some kind of text :) 

Acceptance Criteria:
- Everything displayed in the scribble does not need to be described here (e.g. _The video has a play button centered_)
- What happens when the video is playing? Will the play-button disappear or change into a "stop-button"? Can the user somehow abort playing the video?
- In the scribble and acceptance criteria is not shown/mentioned how the user can switch between the video feed and the form to enter a new video.
