### ISSUE TITLE
#19 Add styling

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#31]
# Value Proposition

**As a** user
**I want to** have a great visual experience
**So that** I can use the app more with more visual pleasure

# Description

The app will have a pleasurable appearance.

# Acceptance Criteria

- [ ] The app is looking good

# Tasks

- [ ] Add styling
- [ ] Add `Typography` component
- [ ] Add Global Styling
- [ ] Add transitions to playlist videos

# Complexity

XL
