### ISSUE TITLE
#16 Create fake login for parents

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#32]
# Value Proposition

**As a** user
**I want to** have a login for parents
**So that** only parents can add, delete and edit videos

# Description

![Image](https://user-images.githubusercontent.com/101993818/187445103-c2496175-cfc5-49bf-87fd-7dd437fd7fbf.png)

![Image](https://user-images.githubusercontent.com/101993818/187448063-97ac8c9d-ead2-4d71-b187-1d50092d1c68.png)

# Acceptance Criteria

- [x] A login form 
- [x] If Username and Password are correct the user will be logged in
- [x] A create account form
- [x] User can only create account if is 18 or older
- [x] After a new account was created, will be redirected and can log in
- [x] After creating an account, the user will be redirected to login page
- [x] After creating an account, a confirmation message pops up
- [x] After login, the user will be redirected to the Create Page
- [x] Just logged-in user can add, edit and delete videos

# Tasks

- [x] Create Create Account Page
- [x] Create Login Page
- [x] Create `Login` component
- [x] Create Login form
- [x] Create Create Account form
- [x] Validate Forms
- [x] Create Store for user data
- [x] Check if user is logged in 
- [x] Add conditions if user is logged-in, he can add, edit or delete videos

# Complexity

XXL
