### ISSUE TITLE
#17 Add category tags to explore page

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#36]
# Value Proposition

**As a** user
**I want to** see all category at a glance
**So that** I can choose the category that I want see videos to

# Description

![Image](https://user-images.githubusercontent.com/101993818/188024603-7f01608e-5237-44af-87e6-6c01f3e4ae41.png)

# Acceptance Criteria

- [x] All categories are displayed as tags
- [x] The categories can be scrolled horizontally
- [x] Clicking on a category to all videos of the category

# Tasks

- [x] Add container for scrolling tags horizontally
- [x] Map through all tags and display them
- [x] On click redirect to feed with videos related to the category

# Complexity

M
