### ISSUE TITLE
#18 Redesign Channel playlists

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#37]
# Value Proposition

**As a** user
**I want to** have a user friendly experience while searching for a channel playlist
**So that** I can more easily choose playlists and add videos 

# Description

![Image](https://user-images.githubusercontent.com/101993818/188026749-7f5dca28-7f58-4f28-af08-8b081793febe.png)

# Acceptance Criteria

- [x] Another channel page with all playlists
- [x] The playlists are horizontally scrollable
- [x] When adding a video a module pops up to ask for a category the video should assigned to
- [x] When module pops up, the background gets darker
- [x] The number of playlists is displayed

# Tasks

- [x] Create a new page for a channel and it's playlists
- [x] Add horizontal scroll to playlists
- [x] Create module to ask for category
- [x] Assign category to related video
- [x] Add overlay while category module is visible
- [x] Count number of playlists and display them
- [x] Add back button

# Complexity

XL
