### ISSUE TITLE
#3 Add navigation

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#4]
# Value Proposition

**As a** user
**I want to** see a navigation
**So that** I can switch between the create page and the home page

# Description

![Image](https://user-images.githubusercontent.com/101993818/184818905-5668018a-56e6-4e39-9338-b4c7458fcd02.png)

# Acceptance Criteria

- [x] When clicking on a nav button, change the page belonging to the button
- [x] When clicking on a nav button, the icon is filled and the other is unfilled
- [x] The navbar sticks to the bottom of the viewport
- [x] The titles of the respective pages are at the top

# Tasks

- [x] Create a ```Navbar``` component
- [x] Add icons and titles to navbar
- [x] Fix the navbar at the bottom of the viewport
- [x] Add onClick function to toggle between filled and unfilled
- [x] Add function to switch between pages
- [x] Add page titles
- [ ] Write test to check if onClick the respective page is shown
- [ ] Write test to check if onClick the icon is filled and other unfilled

# Complexity

L

**Comment by j-eick** [comment]
Nice work  ✅ 

Minor detail: Try not to use "could/should/would..."
The navbar ~~should~~ stick on the bottom of the viewport.
➡️ The navbar sticks to the bottom of the viewport.

**Comment by A11yship** [comment]
Looks good.
In the Value Proposition you write "I want to" two times.

**Comment by ahohnsen** [comment]
You got already some great suggestions :) just wanted to add that everything which is visible in the scribble does not need to be inside your acceptance criteria, e.g. :

>  An icon and title("Home") for the home page
> An icon and title("Create") for the create page
