### ISSUE TITLE
#20 Responsive Design

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#42]
# Value Proposition

**As a** user
**I want to** have a great visual experience on different devices
**So that** I can use the app more with more visual pleasure

# Description

The app will have a pleasurable appearance on all devices

# Acceptance Criteria

- [ ] The app is looking good on different devices

# Tasks

- [ ] Add media queries at breakpoints (375px, 576px, 768px, 992px, 1200px)
- [ ] Change styling at breakpoints

# Complexity

L
