### ISSUE TITLE
#4 Delete video card

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#5]
# Value Proposition

**As a** user
**I want to** delete videos in my feed
**So that** I won't see them in my feed anymore

# Description

![Delete button](https://user-images.githubusercontent.com/101993818/184670074-81fe508a-c8f5-4065-b7a7-fdfd0cfc5971.png)

![Delete pop-up message](https://user-images.githubusercontent.com/101993818/184670087-947bf9d4-52d2-4bae-b288-4e3ffb37575f.png)

# Acceptance Criteria

- [x] On click on the delete button, a popup is displayed to confirm the delete
- [x] The data for the video card will be deleted as well

# Tasks

- [x] Add a delete icon at top-right of every video card
- [x] Add onClick function to delete the video card
- [x] Add popup with question text, cancel button and delete button
- [ ] Write test to check if the video card is deleted after clicking on delete button 
- [x] Write test to check if the popup is showing after clicking on delete button 

# Complexity

L

**Comment by RobertBReich** [comment]
Hy Vlady,
clean and simple. 😃

cheers
R.

**Comment by ahohnsen** [comment]
Hey Vlady,

Well done! Just one comment: I still do not know what the little box at the bottom of the video card is supposed to be 🤔 maybe you can make that more clear in your scribble.

In your acceptance criteria you do not need to write what is already visible in the scribble (e.g. An delete button is on every video card at the top-right corner). Maybe it would be also nice if the video is not deleted instantly. When the user clicks on the delete button, a modal could open where the user needs to confirm deleting the video or he/she can abort the process. 🙂
