### ISSUE TITLE
#5 Edit video card title

### ISSUE THREAD

**Issue by Gw3i** [Gw3i/capstone-project#6]
# Value Proposition

**As a** user
**I want to** edit the video card title
**So that** I can change the title, if there is a typo or misunderstandings

# Description

![Edit card title](https://user-images.githubusercontent.com/101993818/184624473-70d041cb-b388-40db-a48e-8b30655e550e.png)

![Edit card page](https://user-images.githubusercontent.com/101993818/184626754-8962e351-7282-407c-8128-6d7be3cf855d.png)

# Acceptance Criteria

- [x] Each card has an edit button on the top-right corner
- [x] Clicking on the button opens an edit page
- [x] On the edit page is a form and a headline("Edit video title")
- [x] The edit form includes an input field for the video card's title
- [x] The field is filled with the respective value of this video card
- [x] Add validation to the input field
- [x] There is a cancel button that redirects back to the home page
- [x] After submitting the form, the updated  video card title is saved persistently
- [x] After submitting the form, the user is redirected to home page

# Tasks

- [x] Add a edit icon at top-right of every video card
- [x] Add OnClick function redirecting to edit page
- [x] Add edit page with a form and headline
- [x] Add Cancel and Submit button
- [x] Handle state of the input field to show previous value 
- [ ] Write tests to check if the the buttons redirecting to home page
- [ ] Write tests to check if the previous value is shown in the input fiel
- [ ] Write tests to check if the video title was updated

# Complexity

XL

**Comment by RobertBReich** [comment]
Hi Vlady,

small typo in "So that " + i + " can change the title...
AC 2: opens "an" not "and" edit page

looks good.

cheers
R.

**Comment by ahohnsen** [comment]
Hey Vlady,

You could shorten the acceptance criteria a bit (eliminate what is already visible in the scribble). Other than that it is very well written :)
